app/urls.py
from django.conf.urls import url, include
from app import views, api_views


urlpatterns = [
    url(r'^\Z', views.Home.as_view(), name='home'),
    url(r'^app/$', views.Home.as_view(), name='dashboard'),
    url(r'^dashboard/$', views.Dashboard.as_view(), name='dashboard'),
    url(r'^user_account_update/$', views.UserAccountUpdate.as_view(),
        name='user_account_update'),
    url(r'^our-products/$', views.OurProducts.as_view(), name='our-products'),
    url(r'^my-products/$', views.MyProducts.as_view(), name='my-products'),

    url(r'^user-cart/$', views.SolarComponent.as_view(), name='user-cart'),

    url(r'^my-quotes/$', views.MyQuotes.as_view(), name='my-quotes'),
    url(r'^my-account/$', views.UserAccount.as_view(), name='my-account'),
    url(r'^pvt-order/$', views.OrderPVTSystem.as_view(), name='pvt-order'),
    url(r'^geyser-order/$', views.OrderGeyser.as_view(), name='geyser-order'),
    url(r'^order-quotes/(?P<order_number>[0-9A-Fa-f-]+)/(?P<status>[0-9])/$',
        views.OrderQuotes.as_view(),
        name='order-quotes'),
    url(r'^add-component/$', views.AddComponent.as_view(),
        name='add-component'),
    url(r'^register/$', views.Register.as_view(), name='register'),
    url(r'^order/$', views.ClientOrder.as_view(), name='order'),
    url(r'^client-info/$', views.ClientOrder.as_view(), name='client-info'),
    url(r'^products/$', views.OurProducts.as_view(), name='our_products'),
    url(r'^products/component/$', views.SolarComponent.as_view(),
        name='component'),
    url(r'^register/$', views.Register.as_view(), name='register'),

    url(r'^view-slip/(?P<generate>[0-9A-Fa-f-]+)/(?P<pdf>[0-9])/$',
        views.DisplayPDF.as_view(), name='slips'),
    url(r'api/get_brand/(?P<brand_id>\d+)/$',
        api_views.GetProductBrand.as_view(), name='get_brand'),
    url(r'^email/(?P<uuid>[0-9A-Fa-f-]+)/(?P<order>[0-9])/$',
        views.SendEmail.as_view(), name='email'),

    url(r'api/get_order_details/(?P<order_number>[0-9A-Fa-f-]+)/$',
        api_views.GetOrderDetails.as_view(), name='get_order_details'),
    url(r'api/get_systemorder_details/(?P<order_number>[0-9A-Fa-f-]+)/$',
        api_views.GetSystemOrderDetails.as_view(), name='get_systemorder_details'),
    url(r'api/get_client_details/(?P<id>\d+)/$',
        api_views.GetClientDetails.as_view(), name='get_client_details'),
    url(r'api/get_client_address/(?P<id>\d+)/$',
        api_views.GetClientAddress.as_view(), name='get_client_address'),
    url(r'my_products_data/$', api_views.GetMyProducts.as_view(), 
        name='my_products_data'),
    url(r'all_products_data/$', views.AllProductsData.as_view(), 
        name='all_products_data'),
]

energyspazr/urls.py
from django.conf.urls import include, url
from django.urls import reverse, reverse_lazy
from django.contrib import admin
from django.contrib.auth import views as auth_views

from registration.backends.hmac.views import RegistrationView

from app import forms
from app import views

urlpatterns = [
    url(r'^\Z', include('app.urls')),
    url(r'^app/', include('app.urls')),

    url(r'^accounts/signin/$', auth_views.login,
        {'template_name': 'registration/signin.html',
         'authentication_form': forms.SigninForm,
         'redirect_authenticated_user': True}, name='signin'),

    url(r'^accounts/signup/$', RegistrationView.as_view(
        template_name='registration/signup.html',
        form_class=forms.SignupForm), name='signup'),

    url(r'^accounts/resend/$', RegistrationView.as_view(
        template_name='registration/resend_activation_form.html',
        form_class=forms.ResendForm), name='resend'),

    url(r'^accounts/forgot-password/$',
        auth_views.PasswordResetView.as_view(
            template_name='reset/forgot_pass.html',
            email_template_name='reset/password_reset_email.html',
            success_url=reverse_lazy('pass-reset-send'),
            form_class=forms.ForgotPassForm), name='forgot-pass'),
    url(r'^accounts/password-reset-send/$',
        auth_views.PasswordResetDoneView.as_view(
            template_name='reset/pass_reset_send.html'), name='pass-reset-send'),
    url(r'^accounts/set-password/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth_views.PasswordResetConfirmView.as_view(
            form_class=forms.SetPasswordForm,
            template_name='reset/set_pass.html',
            success_url=reverse_lazy('reset-pass-done')), name='set-password'),
    url(r'^accounts/reset-password-complete/$',
        auth_views.PasswordResetCompleteView.as_view(
            template_name='reset/reset_pass_done.html'), name='reset-pass-done'),

    url(r'^accounts/activate/(?P<activation_key>[-:\w]+)/$',
        views.ActivateUser.as_view(), name='registration_activate'),

    url(r'^accounts/', include('registration.backends.hmac.urls')),
    url('^accounts/', include('django.contrib.auth.urls')),
    url(r'^admin/', admin.site.urls),
]

app/forms.py
# Django
from django.contrib.auth import forms as auth_forms
from django.contrib.auth.models import User
from django import forms
from django.forms import ModelForm

# Crispy forms
from crispy_forms.bootstrap import FormActions
from crispy_forms.helper import FormHelper, Layout
from crispy_forms.layout import Submit, HTML, Div, Field, Button

# Local Django
from app import models


class SetPasswordForm(auth_forms.SetPasswordForm):
    def __init__(self, *args, **kwargs):
        super(SetPasswordForm, self).__init__(*args, **kwargs)

        for fieldname in ['new_password1', 'new_password2']:
            self.fields[fieldname].help_text = None

    helper = FormHelper()
    helper.form_method = 'POST'
    helper.form_class = 'login-form'
    helper.form_show_labels = False
    helper.layout = Layout(
        HTML('<h3 class="login-head">'
             'Set New Password</h3> '),
        Div(
            Field('new_password1', css_class='form-control text-center',
                  placeholder='Enter New Password', autofocus=True),
            css_class='form-group'
        ),
        Div(
            Field('new_password2', css_class='form-control text-center',
                  placeholder='Confirm New Password'),
            css_class='form-group'
        ),
        Div(
            FormActions(
                Submit('send', 'SUBMIT', css_class='btn btn-primary btn-block')),
            css_class='form-group'
        ),
        Div(
            Div(
                HTML('<br />\
                <p class="semibold-text mb-0">'
                     "<a href='{% url 'signin' %}'>\
                     <i class='fa fa-angle-left fa-fw'></i>\
                     Back to Login\
                     </a>\
                </p>")
            ),
            css_class='form-group text-center mt-20'
        )
    )


class ForgotPassForm(auth_forms.PasswordResetForm):

    helper = FormHelper()
    helper.form_method = 'POST'
    helper.form_class = 'login-form'
    helper.form_show_labels = False
    helper.layout = Layout(
        HTML('<h3 class="login-head">'
             'Forgot Password?</h3> <br />'),
        Div(
            Field('email', css_class='form-control text-center',
                  placeholder='Email Address', autofocus=True),
            css_class='form-group'
        ),
        Div(
            HTML('<br />'),
            FormActions(
                Submit('send', 'RESET', css_class='btn btn-primary btn-block')),
            css_class='form-group'
        ),
        Div(
            Div(
                HTML('<br />\
                <p class="semibold-text mb-0">'
                     "<a href='{% url 'signin' %}'>\
                     <i class='fa fa-angle-left fa-fw'></i>\
                     Back to Login\
                     </a>\
                </p>")
            ),
            css_class='form-group text-center mt-20'
        )
    )


class SigninForm(auth_forms.AuthenticationForm):

    class Meta(auth_forms.AuthenticationForm):
        model = User
        fields = ['username', 'password']

    helper = FormHelper()
    helper.form_method = 'POST'
    helper.form_class = 'login-form'
    helper.form_show_labels = False
    helper.layout = Layout(
        HTML('<h3 class="login-head"><i class="fa fa-lg fa-fw fa-user">'
             '</i>SIGN IN</h3>'),
        Div(
            Field('username', css_class='form-control text-center',
                  placeholder='Username', autofocus=True),
            css_class='form-group'
        ),
        Div(
            Field('password', placeholder='Password',
                  css_class='form-control text-center'),
            css_class='form-group'
        ),
        Div(
            Div(
                Div(
                    HTML('<label class="semibold-text">'
                         '<input type="checkbox"></label>'),
                    css_class='animated-checkbox'
                ),
                HTML('<p class="semibold-text mb-0">'
                     "<a href='{% url 'forgot-pass' %}'>Forgot Password?</a></p>"),
                css_class='utility'
            ),
            css_class='form-group'
        ),
        Div(
            FormActions(Submit('login', 'SIGN IN',
                               css_class='btn btn-primary btn-block')),
            css_class='form-group btn-container'
        ),
        Div(
            Div(
                HTML('<br /><p class="semibold-text mb-0">'
                     "<a href='{% url 'signup' %}'>Not Registered?</a></p>")
            ),
            css_class='form-group text-center'
        )
    )


class SignupForm(auth_forms.UserCreationForm):

    def __init__(self, *args, **kwargs):
        super(SignupForm, self).__init__(*args, **kwargs)

        for fieldname in ['username', 'password1', 'password2']:
            self.fields[fieldname].help_text = None

    class Meta:
        model = User
        fields = ['username', 'email']

    helper = FormHelper()
    helper.form_method = 'POST'
    helper.form_show_labels = False

    helper.layout = Layout(
        HTML('<h3 class="login-head"><i class="fa fa-lg fa-fw fa-user">'
             '</i>SIGN UP</h3>'),
        Div(
            Div(
                Field('username', css_class='form-control text-center',
                      placeholder='Username'),
                css_class='col-md-12'
            ),
            css_class='row mb-20'
        ),
        Div(
            Div(
                Field('email', css_class='form-control text-center',
                      placeholder='Email Address'),
                css_class='col-md-12'
            ),
            css_class='row mb-20'
        ),
        Div(
            Div(
                Field('password1', css_class='form-control text-center ',
                      placeholder='Password'),
                css_class='col-md-12'
            ),
            css_class='row mb-20'
        ),
        Div(
            Div(
                Field('password2', css_class='form-control text-center ',
                      placeholder='Confirm Password'),
                css_class='col-md-12'
            ),
            css_class='row mb-20'
        ),
        Div(
            FormActions(Submit('signup', 'SIGN UP',
                               css_class='btn btn-primary btn-block')),
            css_class='form-group btn-container'
        ),
        Div(
            Div(
                HTML('<br /><p class="semibold-text mb-0 text-center">'
                     "<a href='{% url 'signin' %}'>Already Registered?</a></p>")
            ),
            css_class='form-group'
        )
    )


class UserAccountUpdateForm(ModelForm):
    building_name = forms.CharField(max_length=30)
    street_name = forms.CharField(max_length=30)
    province = forms.ChoiceField(choices=(), required=True)
    roles = forms.ChoiceField(choices=(), required=True)
    city = forms.CharField(max_length=30)
    suburb = forms.CharField(max_length=30)
    zip_code = forms.CharField(max_length=10)

    def __init__(self, p_choices, r_choices, *args, **kwargs):
        super(UserAccountUpdateForm, self).__init__(*args, **kwargs)
        self.fields['province'].choices = p_choices
        self.fields['roles'].choices = r_choices

    class Meta:
        model = models.SpazrUser
        fields = ['company_name', 'company_reg', 'contact_number',
                  'web_address']

    helper = FormHelper()
    helper.form_method = 'POST'
    helper.form_show_labels = False

    helper.layout = Layout(
        HTML('<h3 class="login-head">ACCOUNT DETAILS</h3>'),
        Div(
            Div(
                HTML('<h5 class="text-right">Select User Type</h5>'),
                css_class='col-md-6'
            ),
            Div(
                Field('roles', css_class='form-control text-center ',
                      placeholder='Role(s)'),
                css_class='col-md-6 text-center'
            ),
            css_class='row mb-20'
        ),
        Div(
            Div(
                Field('company_name', css_class='form-control text-center',
                      placeholder='Compay Name'), css_class='col-md-6'
            ),
            Div(
                Field('company_reg', css_class='form-control text-center ',
                      placeholder='Company Reg. Number'), css_class='col-md-6'
            ),
            css_class='row mb-20'
        ),
        Div(
            Div(
                Field('contact_number', css_class='form-control text-center ',
                      placeholder='Contact Number'), css_class='col-md-6'
            ),
            Div(
                Field('web_address', css_class='form-control text-center ',
                      placeholder='Web Address'), css_class='col-md-6'
            ),
            css_class='row mb-20'
        ),
        HTML('<h5 class="text-center">Physical Address</h5><hr>'),
        Div(
            Div(
                Field('building_name', css_class='form-control text-center ',
                      placeholder='Building Name'), css_class='col-md-6'
            ),
            Div(
                Field('street_name', css_class='form-control text-center ',
                      placeholder='Street Name'), css_class='col-md-6'
            ),
            css_class='row mb-20'
        ),
        Div(
            Div(
                Field('province', css_class='form-control text-center ',
                      placeholder='Provice'), css_class='col-md-6 text-center'
            ),
            Div(
                Field('city', css_class='form-control text-center ',
                      placeholder='City'), css_class='col-md-6 '
            ),
            css_class='row mb-20'
        ),
        Div(
            Div(
                Field('suburb', css_class='form-control text-center ',
                      placeholder='Suburb'), css_class='col-md-6'
            ),
            Div(
                Field('zip_code', css_class='form-control text-center ',

app/templates/app/supplier/account.html
{% extends "app/supplier/layout.html" %}

{% load i18n %}
{% load crispy_forms_tags %}
{% load staticfiles %}

{% block content %}
      
      <div class="content-wrapper">
        <div class="page-title">
          <div>
            <h1><i class="fa fa-user"></i>  Account Settings </h1>
          </div>
          <div>
            <ul class="breadcrumb">
              <li><i class="fa fa-home fa-lg"></i></li>
              <li><a href="">Account Settings</a></li>
            </ul>
          </div>
        </div>
        <div class="row zoomIn animated">
          <div class="col-md-12">
            <div class="panel panel-primary">
              <div class="panel-heading text-center">
                <h3 class="panel-title">Profile</h3>
              </div>
                <div class="panel-body">
                    {% crispy form %}
                </div>
            </div>
          </div>
        </div>
      </div>
  
  {% endblock content %}
  {% block extrajs %}
{% load staticfiles %}
<script type="text/javascript" src="{% static 'app/js/plugins/select2.min.js' %}"></script>
<script type="text/javascript">
    $('#id_province').select2();
    
    $("#id_company_reg").prop("readonly", true);
    $("#id_username").prop("readonly", true);
    $("#submit-id-btn_delete").prop("diabled", true);
    
    var username = "{{user.user|safe}}";
    var email = "{{user.user.email|safe}}";
    var company_name = "{{user.company_name|safe}}";
    var company_reg = "{{user.company_reg|safe}}";
    var contact_number = "{{user.contact_number|safe}}";
    var web_address = "{{user.web_address|safe}}";
    var building  = "{{address.building_name|safe}}";
    var street  = "{{address.street_name|safe}}";
    var city  = "{{address.city|safe}}";
    var suburb  = "{{address.suburb|safe}}";
    var zip  = "{{address.zip_code|safe}}";
    //console.log("Address " + zip);
    $("#id_username").prop("value", username);
    $("#id_email").prop("value", email);
    $("#id_company_name").prop("value", company_name);
    $("#id_company_reg").prop("value", company_reg);
    $("#id_contact_number").prop("value", contact_number);
    $("#id_web_address").prop("value", web_address);
    $("#id_building_name").prop("value", building);
    $("#id_street_name").prop("value", street);
    $("#id_city").prop("value", city);
    $("#id_suburb").prop("value", suburb);
    $("#id_zip_code").prop("value", zip);
</script>
{% endblock%}

app/templates/app/supplier/dashboard.html
{% extends "app/supplier/layout.html" %}

{% block content %}
      
      <div class="content-wrapper">
        <div class="page-title">
          <div>
            <h1><i class="fa fa-dashboard"></i> Dashboard</h1>
          </div>
          <div>
            <ul class="breadcrumb">
              <li><i class="fa fa-home fa-lg"></i></li>
              <li><a href="">Dashboard</a></li>
            </ul>
          </div>
        </div>
        <div class="row zoomIn animated">
          <div class="col-md-6">
            <div class="panel panel-primary">
              <div class="panel-heading text-center">
                <h3 class="panel-title">QUOTE REQUESTS</h3>
              </div>
              <div class="panel-body">Panel content</div>
            </div>
          </div>
          <div class="col-md-6">
            <div class="panel panel-primary">
              <div class="panel-heading text-center">
                <h3 class="panel-title">NEW ORDERS</h3>
              </div>
              <div class="panel-body">Panel content</div>
            </div>
          </div>
          <div class="col-md-12">
            <div class="panel panel-primary">
              <div class="panel-heading text-center">
                <h3 class="panel-title">STATISTICS</h3>
              </div>
              <div class="panel-body">Panel content</div>
            </div>
          </div>
        </div>
      </div>
  
  {% endblock content %}

app/templates/app/supplier/layout.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {% load staticfiles %}
    <link rel="shortcut icon" type="image/png" href="{% static 'common/icon.png' %}"/>
    <title>
      {% block title %}
      energyspazr.com
      {% endblock%}
    </title>
    <!-- CSS-->
    <link rel="stylesheet" type="text/css" href="{% static 'app/css/bootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'app/css/main.cs' %}s">
    <link rel="stylesheet" type="text/css" href="{% static 'app/css/custom.cs' %}s">
  </head>
  <body class="sidebar-mini fixed">
    <div class="wrapper">
      {% include "app/header_navbar.html" %} 
      {% include "app/supplier/side_navbar.html" %}
      {% block content %}
      {% endblock content %}
    </div>
    <!-- Javascripts-->
    {% include 'app/js.html' %}
    {% block extrajs %}
    {% load staticfiles %}
    <script type="text/javascript" src="{% static 'app/js/plugins/select2.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'app/js/plugins/jquery.dataTables.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'app/js/plugins/dataTables.bootstrap.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'app/js/quotes.js' %}"></script>
    {% endblock %}
  </body>
</html>

app/templates/app/supplier/products.html
{% extends "app/supplier/layout.html" %} {% load i18n %} {% load humanize %} {% load crispy_forms_tags %} {% load staticfiles%}
{% block content %}
<div class="content-wrapper">
  <div class="page-title">
    <div>
      <h1><i class="fa fa-edit"></i> Products</h1>
    </div>
    <div>
      <ul class="breadcrumb">
        <li><i class="fa fa-home fa-lg"></i></li>
        <li><a href="">Products</a></li>
      </ul>
    </div>
  </div>
  <div class="row zoomIn animated">
    <div class="col-md-12 zoomIn animated card" id='my_products'>
      <div class="card-title-w-btn">
        <h4 class="title">Select one product to view details or click new to add a product not listed below.</h4>
        <p>
          <a class="btn btn-primary icon-btn" id="btn_add">
            <i class="fa fa-plus"></i>Add
          </a>
        </p>
      </div>
      <div class="card-body">
        <table class="table table-hover table-bordered" id="table_my_products">
          <thead>
            <tr>
              <th data-field="product_name" class='col-md-3 text-center'>Name</th>
              <th data-field="product_brand" class='col-md-3 text-center'>Brand</th>
              <th data-field="product_dimensions" class='col-md-3 text-center'>Dimensions</th>
              <th data-field="product_price" class='col-md-2 text-center'>Price</th>
              <th data-field="product_delete" class='col-md-1 text-center'>Delete</th>
            </tr>
          </thead>
          <tbody>
            {% for product in my_products %}
            <tr value={{ product.pk }}>
              <td class="text-center">{{ product.product__brand__product__name }}</td>
              <td class="text-center">{{ product.product__brand__name__name }}</td>
              <td>
                <ul>
                  {% for dimension in product.product__dimensions %}
                  <li>{{ dimension.name }}: {{ dimension.value }}</li>
                  {% endfor %}
                </ul>
              </td>
              <td class="text-center">R{{ product.price }}</td>
              <td class="text-center">
                <a class="btn btn-sm btn-danger" href="#">
                      <i class="fa fa-2x fa-trash"></i>
                  </a>
              </td>
            </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
    </div>
    <div class="col-md-12 zoomIn animated card" id='all_products'>
      <div class="card-title-w-btn">
        <h4 class="title">Select one product to view details or click new to add a product not listed below.</h4>
        <p>
          <a class="btn btn-primary icon-btn" id="btn_add_new">
            <i class="fa fa-plus"></i>New
          </a>
          <a class="btn btn-warning icon-btn" id="btn_products_back">
            <i class="fa fa-backward"></i>Back
          </a>
        </p>
      </div>
      <div class="card-body">
        <table class="table table-hover table-bordered highlight" id="table_all_products">
        </table>
      </div>
    </div>
    <div class="col-md-12 zoomIn animated card" id='add_products'>
      <div class="card-title-w-btn">
        <h3 class="title">All Products</h3>
        <p>
          <a class="btn btn-warning icon-btn" href="{% url 'my-products' %}">
            <i class="fa fa-backward"></i>Back
          </a>
        </p>
      </div>
      <div class="card-body">
        <table class="table table-hover table-bordered" id="table_my_products">
          <thead>
            <tr>
              <th class='col-md-5'>Product Name</th>
              <th class='col-md-5'>Product Price</th>
              <th class='col-md-2 text-center'>Actions</th>
            </tr>
          </thead>
          <tbody>
            {% for p in my_products %}
            <tr value={{ p.product.pk }}>
              <td>{{ p.product.name }}</td>
              <td>R{{ p.price|intcomma }}</td>
              <td class='text-center'>
                <div class="btn-group">
                  <a class="btn btn-info btn_edit_product"><i class="fa fa-lg fa-edit"></i></a>
                  <a class="btn btn-warning" href="#"><i class="fa fa-lg fa-trash"></i></a>
                </div>
              </td>
            </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
    </div>
    <div class="col-md-12 zoomIn animated card" id='all_panels'>
      <div class="card-title-w-btn">
        <h3 class="title" id="product-head">Solar Panels</h3>
        <p>
          <a class="btn btn-warning icon-btn" id="btn_panels_back">
            <i class="fa fa-backward"></i>Back
          </a>
        </p>
      </div>
      <div class="card-body">
        <table class="table table-hover table-bordered" id="table_all_panels">
        </table>
        <p class="text-center">
          <a class="btn btn-success icon-btn" id="btn_submit_panels">
            <i class="fa fa-check"></i>Submit
          </a>
        </p>
      </div>
    </div>
    <div class="col-md-12">
      <div class="col-md-3"></div>
      <div class="col-md-6 zoomIn animated card" id='edit_panel'>
        <div class="card-title text-center">
          <h4 class="title">
            Update panel details below.
          </h4>
        </div>
        <div class="card-body">
          {% crispy edit_form %}
        </div>
      </div>
    </div>
    <div class="col-md-12">
      <div class="col-md-3"></div>
      <div class="col-md-6 zoomIn animated card" id='add_new_product'>
        <div class="card-title text-center">
          <h4 class="title">
            Add new product.
          </h4>
        </div>
        <div class="card-body">
          {% crispy new_form %}
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock content %} {% block extrajs %} {{ block.super }}
<script>
  var all_products = {{ json_all_prods|safe }};

</script>
<script type="text/javascript" src="{% static 'app/js/products.js' %}"></script>
{% endblock %}

app/templates/app/supplier/side_navbar.html
      <!-- Side-Nav-->
      <aside class="main-sidebar hidden-print">
        <section class="sidebar">
          <div class="user-panel">
            <div class="pull-left image">
                {% load staticfiles %}
                <img class="img-circle" src="{% static 'common/energyspazr.jpg' %}" alt="energyspazr">
            </div>
            <div class="pull-left info">
                <p><a href="{{ user.web_address }}" target="_blank">{{ user.company_name }}</a></p>
                <p class="designation">
                {% for group in user.user.groups.all %}
                    {{ group.name }}, 
                {% endfor %}
                </p>
            </div>
          </div>
          <!-- Sidebar Menu-->
          <ul class="sidebar-menu">
            <li class="{% if 'dashboard' in request.path %} active {% endif %} hvr-grow"><a href="{% url 'dashboard' %}"><i class="fa fa-dashboard"></i><span>Dashboard</span></a></li>
            <li class="hvr-pulse"><a href="#" class="hvr-bob"><i class="fa fa-reorder"></i><span>Orders</span></a></li>
            <li class="{% if 'my-quotes' in request.path %} active {% endif %} hvr-grow"><a href="{% url 'my-quotes' %}" class="hvr-bob"><i class="fa fa-money"></i><span>Quotes</span></a></li>
            <li class="{% if 'my-products' in request.path %} active {% endif %} hvr-grow"><a href="{% url 'my-products' %}" class="hvr-bob"><i class="fa fa-edit"></i><span>Products</span></a></li>
            <li class="{% if 'my-account' in request.path %} active {% endif %}"><a href="{% url 'my-account' %}"><i class="fa fa-user"></i><span>Account</span></a></li>
          </ul>
        </section>
      </aside>